# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SHADOW_DATABASE_URL: mysql://root:root@localhost:3306/food_app?connection_limit=5&pool_timeout=0

jobs:
  start_mysql:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE food_app;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

  test:
    runs-on: ubuntu-latest

    needs: start_mysql

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE food_app;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: mysql -e 'SHOW DATABASES;' -uroot -proot
      # - run: npm run build --if-present
      # - run: npm test
